CREATE TABLE product (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES client(client_id),
    org_id      BIGINT NOT NULL REFERENCES org(org_id),
    mp_product_id INTEGER NULL,
    name        VARCHAR(500) NOT NULL,
    sku         VARCHAR(255) NULL,
    ean         VARCHAR(100) NULL,
    last_known_price NUMERIC(14,2) NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ NULL
);

CREATE INDEX idx_product_org ON product(org_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_product_org_mp ON product(org_id, mp_product_id) WHERE mp_product_id IS NOT NULL AND deleted_at IS NULL;
