-- Branch-safe guard: some databases may have V31/V32 occupied by other feature migrations,
-- so ensure product exists before applying later product-related migrations.
CREATE TABLE IF NOT EXISTS product (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES client(client_id),
    org_id      BIGINT NOT NULL REFERENCES org(org_id),
    mp_product_id INTEGER NULL,
    name        VARCHAR(500) NOT NULL,
    sku         VARCHAR(255) NULL,
    ean         VARCHAR(100) NULL,
    last_known_price NUMERIC(14,2) NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS idx_product_org
    ON product(org_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_org_mp
    ON product(org_id, mp_product_id)
    WHERE mp_product_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_product_org_sku
    ON product(org_id, lower(sku))
    WHERE deleted_at IS NULL AND sku IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_product_org_ean
    ON product(org_id, ean)
    WHERE deleted_at IS NULL AND ean IS NOT NULL;
