CREATE TABLE product_sync_job (
    sync_job_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT NOT NULL REFERENCES org(org_id),
    status        VARCHAR(16) NOT NULL,
    sync_type     VARCHAR(16) NOT NULL,
    synced        INT NOT NULL DEFAULT 0,
    total         INT NOT NULL DEFAULT 0,
    error_message TEXT,
    filter_from   TIMESTAMPTZ,
    started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at   TIMESTAMPTZ
);

CREATE INDEX idx_product_sync_job_org_started
    ON product_sync_job(org_id, started_at DESC);

CREATE UNIQUE INDEX idx_product_sync_job_org_running
    ON product_sync_job(org_id) WHERE status = 'RUNNING';
